org, repo = (ENV["GITHUB_REPOSITORY"]||"").split("/")
match_org, match_repo = (ENV["MATCH_REPOSITORY"]||"").split("/")

platform :ios do
    lane :init_ci do
        github_action(
          api_token: ENV["GH_PAT"],
          org: org,
          repo: repo,
          match_org: match_org,
          match_repo: match_repo,
          writable_deploy_key: true
        )
    end
    
    lane :release do
        cocoapods(
            clean_install: true,
            podfile: "#{ENV['IOS_BUILD_PATH']}/iOS/"
        )
        
        app_store_connect_api_key(
          key_id: ENV["APPSTORE_KEY_ID"],
          issuer_id: ENV["APPSTORE_ISSUER_ID"],
          key_content: ENV['APPSTORE_P8']
        )
        
        match(
            type: "adhoc",
            storage_mode: "git",
            git_url: "git@github.com:#{match_org}/#{match_repo}.git",
            app_identifier: ENV["IOS_BUNDLE_ID"]
        )
        
#         update_code_signing_settings(
#             use_automatic_signing: true,
#             path: "Builds/iOS/iOS/Unity-iPhone.xcodeproj"
#         )
        
        update_code_signing_settings(
            use_automatic_signing: false,
            team_id: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore_team-id"],
            code_sign_identity: 'iPhone Distribution',
            targets: 'Unity-iPhone',
            path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
            profile_name: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore_profile-name"],
            profile_uuid: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore"]
        )
        
        build_app(
            workspace: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcworkspace",
            scheme: "Unity-iPhone",
            configuration: "Debug",
            export_method: "ad-hoc",
            export_xcargs: "-allowProvisioningUpdates",
            export_team_id: ENV['IOS_BUNDLE_ID'],
            xcargs: "CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO EXPANDED_CODE_SIGN_IDENTITY= -allowProvisioningUpdates",
            export_options: {
                compileBitcode: false,
#                 provisioningProfiles: {
#                     ENV["APP_ID"] => ENV["PROVISIONING_PROFILE_DEVELOPMENT"]
#                 }
            }
        )
        
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
        )
    end
end