org, repo = (ENV["GITHUB_REPOSITORY"]||"").split("/")
match_org, match_repo = (ENV["MATCH_REPOSITORY"]||"").split("/")

platform :ios do
    lane :init_ci do
        github_action(
          api_token: ENV["GH_PAT"],
          org: org,
          repo: repo,
          match_org: match_org,
          match_repo: match_repo,
          writable_deploy_key: true
        )
    end
    
    lane :release do
        match(
            type: "appstore",
            storage_mode: "git",
            git_url: "git@github.com:#{match_org}/#{match_repo}.git",
            app_identifier: ENV["IOS_BUNDLE_ID"]
        )
        
#         update_code_signing_settings(
#             use_automatic_signing: true,
#             path: "Builds/iOS/iOS/Unity-iPhone.xcodeproj"
#         )
        
        update_code_signing_settings(
            use_automatic_signing: false,
            team_id: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore_team-id"],
            code_sign_identity: 'iPhone Distribution',
            targets: 'Unity-iPhone',
            path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
            profile_name: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore_profile-name"],
            profile_uuid: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore"]
        )
        
        build_app(
            project: "Builds/iOS/iOS/Unity-iPhone.xcodeproj",
            scheme: "Unity-iPhone",
            configuration: "Debug",
            export_method: "ad-hoc",
            xcargs: "-allowProvisioningUpdates",
            export_options: {
                compileBitcode: false
            }
        )
        
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
        )
    end
end